In [6]:
import numpy as np
import sys

In [7]:
def min_coin_number(c, l_coins):
    """Calcula el numero minimo de monedas de l_coin necesarias para dar cambio de una cantidad c.
    Devuelve el valor calculado
    
    Args:
        c (int): cantidad a dar cambio
        l_coins (lista): lista de enteros positivos que contiene las monedas
    
    Returns:
        m[i][j] (int): mínimo número de monedas para dar cambio de una cantidad c
    """
    m = {i: {j:0 for j in range(c+1)} for i in range(len(l_coins))}
    
    for i in range(1, c+1): 
        m[0][i] = i
        
    for i in range(1, len(l_coins)):
        m[i][0] = 0 
        
    for i in range(1, len(l_coins)):
        for j in range(1, c+1):
            res = j-l_coins[i]
            if (res >= 0): 
                m[i][j] = min(m[i-1][j], 1+m[i][j-l_coins[i]])
            else:
                m[i][j] = m[i-1][j]
    print(m)
    return m[i][j]

In [8]:
l = [9,6,5,1]
print(len(l))
sys.maxsize

4


9223372036854775807

In [9]:
print(min_coin_number(11, l))

{0: {0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9, 10: 10, 11: 11}, 1: {0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 1, 7: 2, 8: 3, 9: 4, 10: 5, 11: 6}, 2: {0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 1, 6: 1, 7: 2, 8: 3, 9: 4, 10: 2, 11: 2}, 3: {0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 1, 6: 1, 7: 2, 8: 3, 9: 4, 10: 2, 11: 2}}
2


In [10]:
def optimal_change(c, l_coins):
    """Calcula el numero optimo de monedas de l_coin necesarias para dar cambio de una cantidad c
    Devuelve un diccionario con las monedas de cada tipo en l_coin necesarias para dar cambio de una cantidad c
    
    Args:
        c (int): cantidad a dar cambio
        l_coins (lista): lista de enteros positivos que contiene las monedas
    
    Returns:
        d: diccionario con el número de monedas necesario para dar cambio de una cantidad c
    """
    l = len(l_coins)
    d = {i: {j:0 for j in range(l)} for i in range(c+1)}
    
    for i in range(l):
        d[0][i] = 1
        
    for i in range(1, c+1):
        for j in range(l):
            if (i-l_coins[j] >= 0):
                res1 = d[i-l_coins[j]][j]
            else:
                res1 = 0
            if(j>=1):
                res2 = d[i][j-1]
            else:
                res2 = 0
            d[i][j] = res1 + res2
    return d

In [11]:
l2 = [1,2,3]
print (optimal_change(4, l2))

{0: {0: 1, 1: 1, 2: 1}, 1: {0: 1, 1: 1, 2: 1}, 2: {0: 1, 1: 2, 2: 2}, 3: {0: 1, 1: 2, 2: 3}, 4: {0: 1, 1: 3, 2: 4}}


In [12]:
def max_matrix_common_subsequence(str_1, str_2):
    """Calcula la matriz de subsecuencia común más larga entre dos cadenas
    Devuelve la matriz de longitudes de subsecuencias máximas comunes parciales
    
    Args:
        str_1: cadena 1
        str_2: cadena 2
    
    Returns:
        m: matriz de longitudes de subsecuencias máximas comunes parciales
    """
    l1, l2 = len(str_1)+1, len(str_2)+1
    m = [[0 for j in range(l1)] for i in range(l2)]

    for i in range(1, l2):
        for j in range(1, l1):
            if i == 0 or j == 0:
                m[i][j] = 0
            elif str_1[j-1] == str_2[i-1]:
                m[i][j] = m[i-1][j-1] + 1
            else:
                m[i][j] = max(m[i-1][j], m[i][j-1])            
    return m


def max_length_common_subsequence(str_1, str_2):
    """Calcula la matriz de subsecuencia común más larga entre dos cadenas
    Devuelve la matriz de longitudes de subsecuencias máximas comunes parciales
    
    Args:
        str_1: cadena 1
        str_2: cadena 2
    
    Returns:
        m: matriz de longitudes de subsecuencias máximas comunes parciales
    """
    i, j = len(str_1), len(str_2)
    m = max_matrix_common_subsequence(str_1, str_2)
    print(m)
    return m[j][i]

In [13]:
max_length_common_subsequence("bdcb","bacdb")

[[0, 0, 0, 0, 0], [0, 1, 1, 1, 1], [0, 1, 1, 1, 1], [0, 1, 1, 2, 2], [0, 1, 2, 2, 2], [0, 1, 2, 2, 3]]


3

In [14]:
def find_max_common_subsequence(str_1, str_2):
    """Encuentra la subsecuencia común de longitud máxima
    Devuelve la subsecuencia común de longitud máxima
    
    Args:
        str_1: cadena 1
        str_2: cadena 2
    
    Returns:
        cad: array que contiene la subsecuencia común máxima
    """
    j, i = len(str_1), len(str_2)
    m = max_matrix_common_subsequence(str_1, str_2)
    ind = max_length_common_subsequence(str_1, str_2)
    cad = [""]*(ind)
    while (i > 0 and j > 0):
        if str_1[j-1] == str_2[i-1]:
            cad[ind-1] = str_1[j-1]
            i = i-1
            j = j-1
            ind = ind-1
        elif m[i-1][j] > m[i][j-1]:
            i = i-1
        else:
            j = j-1
    return cad

In [15]:
find_max_common_subsequence("pene", "pepe")

[[0, 0, 0, 0, 0], [0, 1, 1, 1, 1], [0, 1, 2, 2, 2], [0, 1, 2, 2, 2], [0, 1, 2, 2, 3]]


['p', 'e', 'e']

In [29]:
def get_min_tree(m,L,R):
    """Funcion que encuentra el arbol minimo entre L y R probando todas las raices posibles
    y usando la matriz m
    Devuelve el valor minimo de C(T LR)
    
    Args:
        m (np.matrix): matriz que contiene los subarboles minimos
        L (int): nodo izquierdo
        R (int): nodo derecho
        
    Returns:
        (float): valor del coste minimo del arbol entre L y R
    """
    
    minimo = np.inf
    root = np.inf
    # guardamos la suma de las probabilidades entr eL y R
    sum_probs = np.sum(m.diagonal()[L:R+1])
    
    # ponemos la raiz en cada i para estudiar el arbol minimo
    for i in range(L,R+1):
        # si la i esta en L estudiamos solo TR
        if(i == L):
            if(minimo > m[i+1,R]):
                minimo = m[i+1,R]
                root = i
        # si la i esta en R estudiamos solo TL
        elif(i == R):
            if(minimo > m[L,i-1]):
                minimo = m[L,i-1]
                root = i
        # si no, estudiamos TL + TR con raiz en i
        else:
            if(minimo > m[L,i-1]+m[i+1,R]):
                minimo = m[L,i-1]+m[i+1,R]
                root = i
            
    return (minimo+sum_probs),root

def optimal_order(l_probs):
    """Funcion que encuentra el arbol minimo entre L y R probando todas las raices posibles
    y usando la matriz m
    Devuelve el valor minimo de C(T LR)
    
    Args:
        l_probs (lista): lista con las probabilidades de cada nodo a insertar en el arbol
        
    Returns:
        m (np.matrix): matriz con los costes minimos de los subarboles
    """
    num_nodos = len(l_probs)
    m = np.zeros((num_nodos,num_nodos))
    m_roots = np.zeros((num_nodos,num_nodos),dtype='int32')
    m.fill(np.inf)
    
    # rellenamos la diagonal con las probabilidades de cada nodo
    for i in range(0,num_nodos):
        m[i,i] = l_probs[i]
    
    # estudiamos la parte superior de la diagonal de la matriz
    for i in range(1,num_nodos):
        for j in range(0,num_nodos):
            if(j+i < num_nodos):
                m[j,j+i], m_roots[j,j+i] = get_min_tree(m,j,j+i)         
    return m,m_roots

In [30]:
m,m_roots = optimal_order([0.1,0.2,0.3,0.4])

j=0
for i in range(0,m.shape[0]):
    print(j,m[i])
    j+=1
j=0
for i in range(0,m.shape[0]):
    print(j,m_roots[i])
    j+=1

0 [0.1 0.4 1.  1.8]
1 [inf 0.2 0.7 1.5]
2 [inf inf 0.3 1. ]
3 [inf inf inf 0.4]
0 [0 1 1 2]
1 [0 0 2 2]
2 [0 0 0 3]
3 [0 0 0 0]


In [31]:
def list_opt_ordering_search_tree(m_roots, l, r):
    
    if(l > r):
        return []
    elif l == r:
        return [l]
    k = m_roots[l,r]
    return [k] + list_opt_ordering_search_tree(m_roots,l,k-1) + list_opt_ordering_search_tree(m_roots,k+1,r)
    
    
    
(list_opt_ordering_search_tree(m_roots,0,3))

[2, 1, 0, 3]

Estimar en detalle el coste computacional del algoritmo usado en la función optimal_order(l_probs).

Observando el código del algoritmo desarrollado observamos que el bucle principal del algoritmo (obviando la inicialización de la diagonal) es un bucle el cual recorre para cada nodo, todos los nodos por lo que el coste computacional de optimal order es O(N * N) lo que es igual a O(N^2). Pero en la práctica, y si cogemos la función `m[j,j+i] = get_min_tree(m,j,j+i)` como la función base de nuestro algoritmo, podemos observar que el coste real del algoritmo es de O((N^2)/2) ya que solo necesitamos rellenar la parte superior de la matriz para obtener el resultado final.

In [32]:
def optimal_change2(c, l_coins):
    aux = {i:0 for i in range(c+1)} 
   
    aux[0] = 1
  
    for i in range(0,len(l_coins)): 
        for j in range(l_coins[i],c+1): 
            aux[j] += aux[j-l_coins[i]] 
  
    return aux[c]

In [20]:
print (optimal_change2(4, l2))

4


In [21]:
print(min_coin_number(4, l2))

{0: {0: 0, 1: 1, 2: 2, 3: 3, 4: 4}, 1: {0: 0, 1: 1, 2: 1, 3: 2, 4: 2}, 2: {0: 0, 1: 1, 2: 1, 3: 1, 4: 2}}
2


In [22]:
m = np.ones((2,2))
m[0,0] = 3
m.diagonal()
m[0,1]

1.0

In [23]:
#Cuestión 2: Longest common substring problem
def max_matrix_common_substring(str_1, str_2):
    l1, l2 = len(str_1)+1, len(str_2)+1
    m = [[0 for i in range(l1)] for j in range(l2)]
    length = 0
    for i in range(1,l2):
        for j in range(1,l1):
            if i == 0 or j == 0:
                m[i][j] = 0
            elif str_1[j-1] == str_2[i-1]:
                m[i][j] = m[i-1][j-1] + 1
                length = max(length, m[i][j])
            else:
                m[i][j] = length
    return m

def max_length_common_substring(str_1, str_2):
    i, j = len(str_1), len(str_2)
    m = max_matrix_common_substring(str_1, str_2)
    print(m)
    return m[j][i]

def find_max_common_substring(str_1, str_2):
    j, i = len(str_1), len(str_2)
    m = max_matrix_common_substring(str_1, str_2)
    ind = max_length_common_substring(str_1, str_2)
    cad = [""]*ind
    while (i > 0 and j > 0):
        if str_1[j-1] == str_2[i-1]:
            cad[ind-1] = str_1[j-1]
            i = i-1
            j = j-1
            ind = ind-1
        elif m[i-1][j] > m[i][j-1]:
            i = i-1
        else:
            j = j-1
    return cad

In [24]:
max_length_common_substring("mala", "ramal")

[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 1, 1, 1], [0, 1, 1, 1, 1], [0, 1, 2, 2, 2], [0, 2, 2, 3, 3]]


3

In [25]:
find_max_common_substring("salsa", "al")

[[0, 0, 0, 0, 0, 0], [0, 0, 1, 1, 1, 1], [0, 1, 1, 2, 2, 2]]


['a', 'l']

In [26]:
m = np.ones((4,4))
m[1,2] = 3
print(m)
print(m.diagonal(1))

[[1. 1. 1. 1.]
 [1. 1. 3. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[1. 3. 1.]
